# Generated by Django 5.0.14 on 2026-06-17 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Campanha')),
                ('active', models.BooleanField(default=False, help_text="Se marcada, substitui os destaques padrão. Ex: 'Coleção Outono/Inverno' ou 'Especial Revestimentos Naturais'.", verbose_name='Ativa')),
                ('featured_title', models.CharField(default='Inspirações em Destaque', max_length=200, verbose_name='Título da Área')),
                ('featured_subtitle', models.TextField(blank=True, default='Seleção exclusiva de revestimentos e acabamentos para transformar seu projeto.', verbose_name='Subtítulo da Área')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='Ícone Bootstrap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description (SEO)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Cliente/Arquiteto')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('text', models.TextField(help_text='Foque em experiências de conforto, luxo e transformação do lar.', verbose_name='Depoimento')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação')),
                ('photo', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Foto (Desktop)')),
                ('mobile_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/mobile/', verbose_name='Foto (Mobile)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('text_color', models.CharField(default='#2E2A28', max_length=7, verbose_name='Cor do Texto')),
                ('image', models.ImageField(help_text='Proporção horizontal larga (ex: 1920x580). Use fotos de ambientes sofisticados e bem iluminados.', upload_to='banners/', verbose_name='Imagem do Banner (Desktop)')),
                ('mobile_image', models.ImageField(blank=True, help_text='Obrigatório para versão mobile. Proporção vertical (ex: 1080x1350).', null=True, upload_to='banners/mobile/', verbose_name='Imagem do Banner (Mobile)')),
                ('link', models.URLField(blank=True, verbose_name='Link (CTA)')),
                ('link_text', models.CharField(blank=True, default='Conheça a Linha', max_length=80, verbose_name='Texto do Botão')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='Deixe em branco para o banner ser Padrão.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='core.campaign', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Descreva a textura, acabamento e a sensação que o material proporciona.', verbose_name='Descrição')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Deixe em branco para 'Consultar Especialista'", max_digits=10, null=True, verbose_name='Preço')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional')),
                ('image', models.ImageField(help_text='Priorize imagens do produto ambientado.', upload_to='products/', verbose_name='Imagem Principal (Desktop)')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='products/mobile/', verbose_name='Imagem Principal (Mobile)')),
                ('unit', models.CharField(default='m²', max_length=30, verbose_name='Unidade de Medida')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Em Destaque')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='Lançamento / Promoção')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('meta_title', models.CharField(blank=True, max_length=150, verbose_name='Meta Title (SEO)')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Selecione os revestimentos/acabamentos desta coleção.', to='core.product', verbose_name='Produtos em Destaque'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagem Extra (Desktop)')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='products/gallery/mobile/', verbose_name='Imagem Extra (Mobile)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['order'],
            },
        ),
    ]
