# Generated by Django 5.0.14 on 2026-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sob_consulta',
            field=models.BooleanField(default=False, help_text="Se marcado, oculta o preço no site e exibe 'Sob Consulta'.", verbose_name='Sob Consulta'),
        ),
    ]
