# Generated by Django 5.0.14 on 2026-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_sob_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_installments',
            field=models.IntegerField(default=1, help_text='Ex: 12 para 12x. Use 1 para sem parcelamento.', verbose_name='Máx. Parcelas'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_display_mode',
            field=models.CharField(choices=[('total', 'Mostrar apenas Total'), ('installment', 'Mostrar apenas Parcela'), ('both', 'Mostrar Total e Parcela')], default='total', max_length=20, verbose_name='Modo de Exibição'),
        ),
    ]
