# Generated by Django 5.0.14 on 2026-08-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_max_installments_product_price_display_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='mobile_image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='Imagem Extra'),
        ),
    ]
