# Generated by Django 5.0.14 on 2026-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('tipo', models.CharField(choices=[('showroom', 'Showroom'), ('escritorio', 'Escritório de Projetos')], default='showroom', max_length=20, verbose_name='Tipo')),
                ('title_eyebrow', models.CharField(blank=True, default='VENHA VISITAR', max_length=100, verbose_name='Texto de Apoio (Eyebrow)')),
                ('title_main', models.CharField(blank=True, default='CONHEÇA NOSSO SHOWROOM', max_length=150, verbose_name='Título Principal')),
                ('card_title', models.CharField(blank=True, default='AGENDE UMA VISITA COM NOSSOS ESPECIALISTAS', max_length=100, verbose_name='Título do Card')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='SP', max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('business_hours', models.TextField(blank=True, help_text='Ex: Seg a Sex: 09h às 18h', verbose_name='Horários de Funcionamento')),
                ('mapa_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Incorporação do Google Maps (Iframe)')),
                ('rota_url', models.URLField(blank=True, max_length=500, verbose_name='URL de Rota do Google Maps')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Unidade / Showroom',
                'verbose_name_plural': 'Unidades / Showrooms',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
