# Generated by Django 5.0.14 on 2026-06-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Marca')),
                ('logo', models.ImageField(upload_to='empresa/marcas/', verbose_name='Logo da Marca')),
                ('em_destaque', models.BooleanField(default=True, help_text='Se marcado, a marca aparecerá no carrossel da home.', verbose_name='Em Destaque')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Marca Parceira',
                'verbose_name_plural': 'Marcas Parceiras',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SobreEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_secao', models.CharField(default='Sobre Nós', max_length=100, verbose_name='Título da Seção')),
                ('texto', models.TextField(verbose_name='Texto Principal')),
                ('imagem_loja', models.ImageField(blank=True, null=True, upload_to='empresa/sobre/', verbose_name='Imagem da Loja')),
            ],
            options={
                'verbose_name': 'Sobre a Empresa',
                'verbose_name_plural': 'Sobre a Empresa',
            },
        ),
    ]
